### ISSUE TITLE
1.88.0.beta1 - Is C++14 support intentionally dropped on macOS?

### ISSUE THREAD

**Issue by cho-m** [boostorg/dll#92]
I was trying out beta for Homebrew (https://github.com/Homebrew/homebrew-core/pull/217231) and saw the following build error for a project using C++14:
```
  In file included from /opt/homebrew/include/boost/dll/runtime_symbol_info.hpp:21:
  /opt/homebrew/include/boost/dll/detail/posix/program_location_impl.hpp:35:13: error: no matching function for call to '_NSGetExecutablePath'
     35 |         if (_NSGetExecutablePath(p.data(), &size) != 0) {
        |             ^~~~~~~~~~~~~~~~~~~~
  /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/usr/include/mach-o/dyld.h:105:12: note: candidate function not viable: 1st argument ('const value_type *' (aka 'const char *')) would lose const qualifier
    105 | extern int _NSGetExecutablePath(char* buf, uint32_t* bufsize)                 __OSX_AVAILABLE_STARTING(__MAC_10_2, __IPHONE_2_0);
        |            ^                    ~~~~~~~~~
```

This was caused by https://github.com/boostorg/dll/commit/9d452d14594749772f2cf601efa37bf9c8f56717 which added:
https://github.com/boostorg/dll/blob/013633d375b8e33b86a4495a9aba132cf5e90de2/include/boost/dll/detail/posix/program_location_impl.hpp#L33-L35

`p.data()` only has `const` return before C++17 so this implicitly sets minimum of C++17 on macOS.

**Comment by apolukhin** [comment]
Many thanks for the bug report!
